spring:
  h2:
    console:
      enabled: true
#      path: /h2
  datasource:
    url: jdbc:h2:~/coindesk
#    url: jdbc:h2:mem:test
    username: test
    password: 123
    driverClassName: org.h2.Driver
  jpa: 
    database-platform: org.hibernate.dialect.H2Dialect
    properties: 
      hibernate: 
        jdbc:
          batch-size: 10
#  web:#    resources:#      static-locations: classpath:templates/, classpath:resources/ , classpath:static/ 
server:     
  port: 8080